### ISSUE TITLE
What about the y intercept?

### ISSUE THREAD

**Issue by LarryBattle** [mengli/leetcode#3]
I enjoyed reading your code for MaxPointsOnALine.java
URL:
https://github.com/mengli/leetcode/blob/master/MaxPointsOnALine.java#L30

After reviewing your code, it seems that it's only comparing the slope value and not including calculation for the x or y intercepts. However, shouldn't you include that in your comparisons since two different lines can have the same slope but different x or y intercepts.

**Comment by mengli** [comment]
Fixed. Thanks!
