### ISSUE TITLE
RemoveDuplicatesfromSortedArray is wrong

### ISSUE THREAD

**Issue by qiutiaoming** [mengli/leetcode#6]
RemoveDuplicatesfromSortedArray

when input is `int[] a = {1,1,2}`
the output array is `{1,2,2}`

I think java array cannot finish this task.

**Comment by mengli** [comment]
Hi qiutiaoming
Actually it is not a real issue. As you know we cannot change the length of a java array and that is why this problem asks us to return an integer value as the new length of the result array. So it will work just fine here.
